import { redirect } from 'next/navigation'
import Link from 'next/link'
import { resolvePortalContext } from '@/lib/portalContext'

export default async function MemberReportsPage() {
  const ctx = await resolvePortalContext()
  if (!ctx.user) redirect('/login')
  if (!ctx.member) redirect('/dashboard')
  const member = ctx.member as { id: string; name: string }

  const { data: reports } = await ctx.db
    .from('reports')
    .select('id, period_type, period_label, generated_at, sent_at, share_token')
    .eq('member_id', member.id)
    .not('sent_at', 'is', null)
    .order('generated_at', { ascending: false })

  const periodLabel: Record<string, string> = {
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    yearly: 'Annual',
  }

  return (
    <div className="p-8 max-w-3xl">
      <div className="mb-8">
        <p className="text-[#C9A227] text-xs tracking-[0.25em] uppercase mb-2">Your Progress</p>
        <h1 className="text-[var(--text)] font-serif text-3xl">Reports</h1>
        <p className="text-[var(--text-3)] text-sm mt-1">
          Generated by Gogo&apos;s AI · Reflects your real attendance, homework, and progress
        </p>
      </div>

      <div className="h-px bg-gradient-to-r from-transparent via-[#C9A227]/40 to-transparent mb-8" />

      {!reports || reports.length === 0 ? (
        <div className="bg-[var(--surface)] border border-[var(--border-color)] rounded p-8 text-center">
          <div className="w-12 h-12 rounded-full border border-[#C9A227]/30 bg-[#C9A227]/5 flex items-center justify-center mx-auto mb-4">
            <span className="text-[#C9A227] text-xl">◆</span>
          </div>
          <h2 className="text-[var(--text)] font-serif text-lg mb-2">No Reports Yet</h2>
          <p className="text-[var(--text-3)] text-sm leading-relaxed">
            Your first report will be delivered after your first month in the program.<br />
            Keep showing up and doing the work.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map((report) => (
            <Link
              key={report.id}
              href={report.share_token ? `/r/${report.share_token}` : `/dashboard/reports/${report.id}`}
              className="block bg-[var(--surface)] border border-[var(--border-color)] rounded p-5 hover:border-[#C9A227]/30 transition-all group"
            >
              <div className="flex items-center justify-between">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-[10px] bg-[var(--border-color)] text-[var(--text-3)] px-2 py-0.5 rounded uppercase tracking-wider">
                      {periodLabel[report.period_type] ?? report.period_type}
                    </span>
                  </div>
                  <h3 className="text-[var(--text)] font-serif text-lg group-hover:text-[#C9A227] transition-colors">
                    {report.period_label}
                  </h3>
                  <p className="text-[var(--text-3)] text-xs mt-1">
                    Delivered {new Date(report.sent_at!).toLocaleDateString('en-US', {
                      month: 'long',
                      day: 'numeric',
                      year: 'numeric',
                    })}
                  </p>
                </div>
                <span className="text-[var(--text-3)] group-hover:text-[#C9A227] text-lg transition-colors">→</span>
              </div>
            </Link>
          ))}
        </div>
      )}

      <div className="mt-8">
        <Link href="/dashboard" className="text-xs text-[var(--text-3)] hover:text-[#C9A227] transition-colors">
          ← Back to dashboard
        </Link>
      </div>
    </div>
  )
}
